"""Local Mumble server (murmurd) lifecycle manager."""

import time

class MumbleServerManager:
    """Manages local mumble-server (murmurd) instances.

    Each instance gets its own config file and systemd service override.
    Config files are written to /etc/mumble-server-gw{n}.ini and managed
    via systemd (mumble-server-gw{n}.service).
    """

    # State constants
    STATE_DISABLED = 'disabled'
    STATE_CONFIGURED = 'configured'
    STATE_RUNNING = 'running'
    STATE_ERROR = 'error'

    def __init__(self, instance_num, config):
        self.num = instance_num
        self.prefix = f'MUMBLE_SERVER_{instance_num}'
        self.config = config
        self.state = self.STATE_DISABLED
        self.error_msg = ''
        self._service_name = f'mumble-server-gw{instance_num}'
        self._config_path = f'/etc/mumble-server-gw{instance_num}.ini'
        self._db_path = f'/var/lib/mumble-server/mumble-server-gw{instance_num}.sqlite'
        self._log_path = f'/var/log/mumble-server/mumble-server-gw{instance_num}.log'
        self._pid_path = f'/var/run/mumble-server/mumble-server-gw{instance_num}.pid'

    def _get_cfg(self, key):
        """Get a config value for this instance."""
        return getattr(self.config, f'{self.prefix}_{key}', None)

    def is_enabled(self):
        return getattr(self.config, f'ENABLE_{self.prefix}', False)

    def write_config(self):
        """Write the mumble-server .ini file for this instance."""
        port = int(self._get_cfg('PORT') or 64738)
        password = str(self._get_cfg('PASSWORD') or '')
        max_users = int(self._get_cfg('MAX_USERS') or 10)
        max_bw = int(self._get_cfg('MAX_BANDWIDTH') or 72000)
        welcome = str(self._get_cfg('WELCOME') or '')
        reg_name = str(self._get_cfg('REGISTER_NAME') or '')
        allow_html = self._get_cfg('ALLOW_HTML')
        opus_thresh = int(self._get_cfg('OPUS_THRESHOLD') or 0)

        lines = [
            '# Auto-generated by Radio Gateway',
            f'# Instance: Mumble Server {self.num}',
            f'# Do not edit — regenerated on each gateway start',
            '',
            f'port={port}',
            f'serverpassword={password}',
            f'bandwidth={max_bw}',
            f'users={max_users}',
            f'opusthreshold={opus_thresh}',
            f'allowhtml={"true" if allow_html else "false"}',
            f'welcometext={welcome}',
            f'registerName={reg_name}',
            f'bonjour=false',
            '',
            '# Disable autoban (gateway pymumble reconnects trigger it)',
            'autobanAttempts=0',
            '',
            '# Long client timeout (pymumble protocol 1.2.4 ping may not satisfy newer murmur)',
            'timeout=300',
            '',
            f'database={self._db_path}',
            f'logfile={self._log_path}',
            f'pidfile={self._pid_path}',
            '',
            '# Auto-generated SSL (mumble-server creates self-signed on first run)',
            '',
        ]

        try:
            import subprocess
            content = '\n'.join(lines) + '\n'
            result = subprocess.run(
                ['sudo', 'tee', self._config_path],
                input=content, capture_output=True, text=True, timeout=5
            )
            if result.returncode != 0:
                self.state = self.STATE_ERROR
                self.error_msg = f'Failed to write config: {result.stderr.strip()}'
                return False
            return True
        except Exception as e:
            self.state = self.STATE_ERROR
            self.error_msg = f'Config write error: {e}'
            return False

    def _setup_systemd_service(self):
        """Create a systemd service override for this instance."""
        import subprocess

        service_file = f'/etc/systemd/system/{self._service_name}.service'
        murmurd_bin = None
        for candidate in ['/usr/sbin/murmurd', '/usr/bin/murmurd',
                          '/usr/sbin/mumble-server', '/usr/bin/mumble-server']:
            try:
                result = subprocess.run(['test', '-x', candidate],
                                        capture_output=True, timeout=2)
                if result.returncode == 0:
                    murmurd_bin = candidate
                    break
            except Exception:
                pass

        if not murmurd_bin:
            # Try 'which' as fallback
            try:
                result = subprocess.run(['which', 'murmurd'], capture_output=True,
                                        text=True, timeout=2)
                if result.returncode == 0:
                    murmurd_bin = result.stdout.strip()
            except Exception:
                pass
            if not murmurd_bin:
                try:
                    result = subprocess.run(['which', 'mumble-server'],
                                            capture_output=True, text=True, timeout=2)
                    if result.returncode == 0:
                        murmurd_bin = result.stdout.strip()
                except Exception:
                    pass

        if not murmurd_bin:
            self.state = self.STATE_ERROR
            self.error_msg = 'murmurd/mumble-server binary not found'
            return False

        # Detect the service user: Arch uses '_mumble-server', Debian uses 'mumble-server'
        import pwd
        svc_user = None
        for candidate_user in ['_mumble-server', 'mumble-server']:
            try:
                pwd.getpwnam(candidate_user)
                svc_user = candidate_user
                break
            except KeyError:
                pass
        if not svc_user:
            self.state = self.STATE_ERROR
            self.error_msg = 'mumble-server system user not found (need _mumble-server or mumble-server)'
            return False

        unit = '\n'.join([
            '[Unit]',
            f'Description=Mumble Server (Gateway Instance {self.num})',
            'After=network.target',
            '',
            '[Service]',
            'Type=simple',
            f'ExecStart={murmurd_bin} -fg -ini {self._config_path}',
            f'User={svc_user}',
            f'Group={svc_user}',
            'Restart=on-failure',
            'RestartSec=5',
            '',
            '[Install]',
            'WantedBy=multi-user.target',
            '',
        ])

        try:
            result = subprocess.run(
                ['sudo', 'tee', service_file],
                input=unit, capture_output=True, text=True, timeout=5
            )
            if result.returncode != 0:
                self.state = self.STATE_ERROR
                self.error_msg = f'Failed to write service: {result.stderr.strip()}'
                return False
            subprocess.run(['sudo', 'systemctl', 'daemon-reload'],
                           capture_output=True, timeout=5)
            return True
        except Exception as e:
            self.state = self.STATE_ERROR
            self.error_msg = f'Service setup error: {e}'
            return False

    def start(self):
        """Write config, set up service, and start the mumble-server instance."""
        import subprocess

        if not self.is_enabled():
            self.state = self.STATE_DISABLED
            return

        self.state = self.STATE_CONFIGURED
        self.error_msg = ''

        # Check if mumble-server package is installed
        try:
            result = subprocess.run(['which', 'murmurd'], capture_output=True,
                                    text=True, timeout=2)
            if result.returncode != 0:
                result = subprocess.run(['which', 'mumble-server'],
                                        capture_output=True, text=True, timeout=2)
            if result.returncode != 0:
                self.state = self.STATE_ERROR
                self.error_msg = 'mumble-server not installed (run scripts/install.sh)'
                return
        except Exception as e:
            self.state = self.STATE_ERROR
            self.error_msg = f'Cannot check for mumble-server: {e}'
            return

        # Stop any existing instance first so config changes (especially port)
        # take effect.  systemctl start is a no-op if the service is already
        # running, so we must explicitly stop+start (restart) every time.
        try:
            subprocess.run(
                ['sudo', 'systemctl', 'stop', f'{self._service_name}.service'],
                capture_output=True, timeout=10
            )
        except Exception:
            pass

        # Ensure directories exist
        for d in ['/var/lib/mumble-server', '/var/log/mumble-server',
                  '/var/run/mumble-server']:
            try:
                subprocess.run(['sudo', 'mkdir', '-p', d],
                               capture_output=True, timeout=3)
            except Exception:
                pass

        # Write config file
        if not self.write_config():
            return

        # Set up systemd service
        if not self._setup_systemd_service():
            return

        autostart = self._get_cfg('AUTOSTART')
        if autostart is False:
            # Configured but not auto-started
            print(f"  Mumble Server {self.num}: configured (autostart=false)")
            return

        # Start the service
        try:
            result = subprocess.run(
                ['sudo', 'systemctl', 'start', f'{self._service_name}.service'],
                capture_output=True, text=True, timeout=10
            )
            if result.returncode != 0:
                self.state = self.STATE_ERROR
                self.error_msg = result.stderr.strip() or 'systemctl start failed'
                return
            # Brief pause then verify
            time.sleep(0.5)
            self._check_running()
        except Exception as e:
            self.state = self.STATE_ERROR
            self.error_msg = f'Start error: {e}'

    def stop(self):
        """Stop the mumble-server instance."""
        import subprocess
        try:
            subprocess.run(
                ['sudo', 'systemctl', 'stop', f'{self._service_name}.service'],
                capture_output=True, timeout=10
            )
        except Exception:
            pass
        self.state = self.STATE_CONFIGURED if self.is_enabled() else self.STATE_DISABLED

    def _check_running(self):
        """Check if the service is actively running."""
        import subprocess
        try:
            result = subprocess.run(
                ['systemctl', 'is-active', f'{self._service_name}.service'],
                capture_output=True, text=True, timeout=3
            )
            if result.stdout.strip() == 'active':
                self.state = self.STATE_RUNNING
            elif self.state != self.STATE_ERROR:
                self.state = self.STATE_ERROR
                # Try to get reason from journal
                try:
                    jr = subprocess.run(
                        ['journalctl', '-u', f'{self._service_name}.service',
                         '-n', '3', '--no-pager', '-q'],
                        capture_output=True, text=True, timeout=3
                    )
                    last_line = jr.stdout.strip().split('\n')[-1] if jr.stdout.strip() else ''
                    self.error_msg = last_line[:80] if last_line else 'service not active'
                except Exception:
                    self.error_msg = 'service not active'
        except Exception as e:
            if self.state != self.STATE_ERROR:
                self.state = self.STATE_ERROR
                self.error_msg = f'status check failed: {e}'

    def check_health(self):
        """Periodic health check — call from status_monitor_loop."""
        if not self.is_enabled():
            self.state = self.STATE_DISABLED
            return
        if self.state == self.STATE_DISABLED:
            return
        self._check_running()

    def get_status(self):
        """Return (state, port) tuple for status bar."""
        port = int(self._get_cfg('PORT') or 64738)
        return self.state, port


